version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: userprofilemanager-db
    environment:
      POSTGRES_DB: userprofiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: userprofilemanager:latest
    container_name: userprofilemanager-app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userprofiledb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
